import { MAHALLELER, SIKAYET_TURLERI } from "@kars/shared";

/** Weighted keyword groups — highest total score wins → maps to department via SIKAYET_TURLERI. */
export type LexGroup = { terms: string[]; weight: number };

/**
 * Issue words citizens use → şikayet türü.
 * Routing: tür → defaultDepartment (Su ve Kan. / Fen / Temizlik / …).
 */
export const TUR_LEXICON: Record<string, LexGroup[]> = {
  "Vidanjör Talebi": [
    {
      terms: [
        "vidanjor",
        "vidanjör",
        "vidanj",
        "vidancor",
        "vidanjorcu",
        "vidanjörcü",
        "vidanjör araci",
        "vidanjor araci",
      ],
      weight: 6,
    },
    {
      terms: [
        "fosseptik",
        "foseptik",
        "fos septik",
        "foseptik dolu",
        "fosseptik dolu",
        "fosseptik tasti",
        "fosseptik taştı",
        "foseptik tasti",
      ],
      weight: 5,
    },
    {
      terms: [
        "vidanjör cagir",
        "vidanjor cagir",
        "vidanjör gelsin",
        "vidanjor gelsin",
        "vidanjör lazım",
        "vidanjor lazim",
        "vidanjör isteriz",
        "vidanjor isteriz",
        "vidanjör talep",
        "vidanjor talep",
      ],
      weight: 7,
    },
    {
      terms: [
        "atik su cek",
        "atık su çek",
        "atiksu cekme",
        "atıksu çekme",
        "pit bosalt",
        "pit boşalt",
        "kuyu bosalt",
        "kuyu boşalt",
        "foseptik bosalt",
        "fosseptik boşalt",
      ],
      weight: 5,
    },
    {
      terms: [
        "vidanjör aracı",
        "vidanjor aracı",
        "vidanjör gönderin",
        "vidanjor gonderin",
        "vidanjör istiyoruz",
        "vidanjor istiyoruz",
        "çekici vidanjör",
        "cekici vidanjor",
        "septik tank",
        "septik dolu",
        "foseptik taşıyor",
        "fosseptik tasiyor",
        "fosseptik kokuyor",
        "foseptik kokuyor",
        "atık su tankı",
        "atik su tanki",
      ],
      weight: 6,
    },
    {
      terms: [
        "kuyu doldu",
        "fosseptik doldu",
        "foseptik doldu",
        "çekim yapılsın",
        "cekim yapilsin",
        "vidanjör randevu",
        "vidanjor randevu",
        "vidanjör ücret",
        "vidanjor ucret",
        "bağınırsak çukuru",
        "bagirsak cukuru",
        "lağım çukuru dolu",
        "lagim cukuru dolu",
      ],
      weight: 5,
    },
    {
      terms: [
        "vidanjör gelsin acil",
        "vidanjor gelsin acil",
        "vidanjör çağırın",
        "vidanjor cagirin",
        "foseptiği boşaltın",
        "foseptigi bosaltin",
        "fosseptiği çekin",
        "fosseptigi cekin",
        "vidanjör sipariş",
        "vidanjor siparis",
        "çekim aracı lazım",
        "cekim araci lazim",
      ],
      weight: 7,
    },
    {
      terms: [
        "sızdırmazlık fosseptik",
        "sizdirmazlik fosseptik",
        "foseptik taşıyor eve",
        "fosseptik tasiyor eve",
        "kuyu dolmuş taşacak",
        "kuyu dolmus tasacak",
        "atik su dolu",
        "atık su dolu",
        "vidanjör numarası",
        "vidanjor numarasi",
        "belediye vidanjörü",
        "belediye vidanjöru",
        "özel vidanjör değil belediye",
        "ozel vidanjor degil",
      ],
      weight: 5,
    },
    {
      terms: [
        "septik temizlensin",
        "çukur dolu çekilsin",
        "cukur dolu cekilsin",
        "vidanjör ücreti ne",
        "vidanjor ucreti ne",
        "randevu vidanjör",
        "randevu vidanjor",
      ],
      weight: 4,
    }
  ],

  "Logar Tıkanıklığı": [
    {
      terms: [
        "logar",
        "rogar",
        "rögar",
        "mazgal",
        "logarlar",
        "rogarlar",
        "baca logar",
        "yol logari",
        "yol logarı",
      ],
      weight: 6,
    },
    {
      terms: [
        "kanalizasyon",
        "kanalizyason",
        "lagim",
        "lağım",
        "atiksuyu",
        "atıksuyu",
        "atik su hatti",
        "atık su hattı",
        "pissu hatti",
        "pis su hattı",
      ],
      weight: 5,
    },
    {
      terms: [
        "logar tasti",
        "logar taştı",
        "logar tasiyor",
        "logar taşıyor",
        "logar patladi",
        "logar patladı",
        "logar akti",
        "logar aktı",
        "logar doldu",
        "rogar tasti",
        "rögar taştı",
      ],
      weight: 7,
    },
    {
      terms: [
        "tikanik",
        "tıkanık",
        "tikandi",
        "tıkandı",
        "tikali",
        "tıkalı",
        "tikandi mi",
        "tikaniklik",
        "tıkanıklık",
        "tikandi logar",
      ],
      weight: 3,
    },
    {
      terms: [
        "pis su",
        "kirli su cikiyor",
        "kirli su çıkıyor",
        "lağım kokusu",
        "lagim kokusu",
        "kanalizasyon kokusu",
        "kotu koku logar",
        "kötü koku logar",
        "evin icine logar",
        "eve logar girdi",
      ],
      weight: 5,
    },
    {
      terms: [
        "rögar kapağı",
        "rogar kapagi",
        "logar kapağı",
        "logar kapagi",
        "logar açılmıyor",
        "logar acilmiyor",
        "tıkanık logar",
        "tikanik logar",
        "logar temizlensin",
        "rogar temizlensin",
        "baca tıkalı",
        "baca tikali",
        "menfez tıkalı",
        "menfez tikali",
      ],
      weight: 6,
    },
    {
      terms: [
        "lağım aktı",
        "lagim akti",
        "lağım patladı",
        "lagim patladi",
        "pis su aktı",
        "pis su akti",
        "kirli su bastı",
        "kirli su basti",
        "kanal taştı",
        "kanal tasti",
        "atıksu taşıyor",
        "atiksu tasiyor",
        "logardan koku",
        "rogardan koku",
        "evin içine lağım",
        "evin icine lagim",
        "tuvalet tersine çalışıyor",
        "tuvalet tersine calisiyor",
        "geri tepiyor lağım",
      ],
      weight: 5,
    },
    {
      terms: [
        "tıkanıklık var",
        "tikaniklik var",
        "akmıyor lağım",
        "akmiyor lagim",
        "dolmuş logar",
        "dolmus logar",
        "taşkın logar",
        "taskin logar",
        "su baskını lağım",
        "su baskini lagim",
      ],
      weight: 4,
    },
    {
      terms: [
        "logar patladı sokak su",
        "logar patladi sokak su",
        "rögar taştı cadde",
        "rogar tasti cadde",
        "lağım bastı evi",
        "lagim basti evi",
        "kanalizasyon geri tepti",
        "tuvaletten geri geliyor",
      ],
      weight: 7,
    },
    {
      terms: [
        "logar kapağı kırık",
        "logar kapagi kirik",
        "logar açık tehlike",
        "logar acik tehlike",
        "çocuk düşebilir logar",
        "cocuk dusebilir logar",
        "logar izgara yok",
        "mazgal yok",
        "yağmurda logar taşıyor",
        "yagmurda logar tasiyor",
        "sağanakta lağım",
        "saganakta lagim",
      ],
      weight: 6,
    },
    {
      terms: [
        "tıkanık gider",
        "tikanik gider",
        "bina gideri tıkalı",
        "bina gideri tikali",
        "ortak gider tıkalı",
        "ortak gider tikali",
        "lağım kokusu dayanılmaz",
        "lagim kokusu dayanilmaz",
        "pis su birikti",
        "kirli su birikti",
        "logar temizleme ekipleri",
        "rogar temizleme",
      ],
      weight: 5,
    },
    {
      terms: [
        "kanal açma",
        "kanal acma",
        "tıkalı kanal",
        "tikali kanal",
        "atıksu taşkını",
        "atiksu taskini",
        "lağım suyu aktı",
        "lagim suyu akti",
        "rögardan fışkırıyor",
        "rogardan fiskiriyor",
      ],
      weight: 4,
    }
  ],

  "Su Arızası": [
    {
      terms: [
        "su boru",
        "su borusu",
        "boru patla",
        "patlak boru",
        "boru patlak",
        "ana boru",
        "su hatti patla",
        "su hattı patla",
        "boru kirildi",
        "boru kırıldı",
      ],
      weight: 7,
    },
    {
      terms: [
        "su kacagi",
        "su kaçağı",
        "su kacak",
        "su kaçak",
        "vana bozul",
        "vana patlak",
        "vana arizali",
        "vana arızalı",
        "su sizintisi",
        "su sızıntısı",
      ],
      weight: 6,
    },
    {
      terms: [
        "su kesik",
        "su kesildi",
        "su yok",
        "susuz kaldik",
        "susuz kaldık",
        "sular kesik",
        "sular kesildi",
        "su gelmiyor",
        "musluktan su yok",
        "gunlerdir su yok",
        "günlerdir su yok",
      ],
      weight: 6,
    },
    {
      terms: [
        "su basinci",
        "su basıncı",
        "basinc yok",
        "basınç yok",
        "damla damla",
        "su zayif",
        "su zayıf",
        "basinc dusuk",
        "basınç düşük",
        "ust kata su cikmiyor",
        "üst kata su çıkmıyor",
      ],
      weight: 5,
    },
    {
      terms: [
        "akinti",
        "akıntı",
        "sızıyor",
        "siziyor",
        "fiskir",
        "fışkır",
        "fiskiriyor",
        "fışkırıyor",
        "su aktı",
        "su akti",
        "su akiyor",
        "su akıyor",
        "kaldırımdan su",
        "kaldirimdan su",
        "yoldan su fışkır",
      ],
      weight: 5,
    },
    {
      terms: [
        "patlak",
        "patladi",
        "patladı",
        "su arizasi",
        "su arızası",
        "su problemi",
        "su sorunu",
        "ici su doldu",
        "bodrum su",
      ],
      weight: 4,
    },
    {
      terms: [
        "musluk",
        "sayac",
        "sayaç",
        "abonelik su",
        "su sayaci",
        "su sayacı",
        "klon su",
        "klorlu su",
        "bulanik su",
        "bulanık su",
        "sari su",
        "sarı su",
        "kokulu su",
      ],
      weight: 3,
    },
    {
      terms: [
        "su",
      ],
      weight: 2,
    },
    {
      terms: [
        "ana hat patladı",
        "ana hat patladi",
        "şebeke suyu yok",
        "sebeke suyu yok",
        "içme suyu yok",
        "icme suyu yok",
        "su şebekesi arızalı",
        "su sebekesi arizali",
        "boru manşonu",
        "boru mansonu",
        "kelepçe patladı",
        "kelepce patladi",
      ],
      weight: 7,
    },
    {
      terms: [
        "su kesintisi",
        "plansız su kesintisi",
        "plansiz su kesintisi",
        "sular akmıyor",
        "sular akmiyor",
        "musluktan gelmiyor",
        "sadece damlıyor",
        "sadece damliyor",
        "su kesildi haber yok",
        "vana açık su yok",
        "vana acik su yok",
      ],
      weight: 6,
    },
    {
      terms: [
        "çamurlu su",
        "camurlu su",
        "paslı su",
        "pasli su",
        "klor kokusu aşırı",
        "klor kokusu asiri",
        "su bulanık",
        "su bulanik",
        "su sarı aktı",
        "su sari akti",
        "su kötü kokuyor",
        "su kotu kokuyor",
        "içilemez su",
        "icilemez su",
        "su kalitesi kötü",
        "su kalitesi kotu",
      ],
      weight: 5,
    },
    {
      terms: [
        "su sayacı arızalı",
        "su sayaci arizali",
        "sayaç dönmüyor",
        "sayac donmuyor",
        "sayaç kaçırıyor",
        "sayac kaciriyor",
        "su abonesi",
        "yeni su aboneliği",
        "yeni su aboneligi",
        "su bağlatma",
        "su baglatma",
        "su açtırma",
        "su actirma",
        "su kapattırma",
        "su kapattirma",
      ],
      weight: 4,
    },
    {
      terms: [
        "hidrofor",
        "depo suyu",
        "su deposu",
        "pompa arızalı",
        "pompa arizali",
        "su pompası",
        "su pompasi",
        "bahçe musluğu",
        "bahce muslugu",
        "yangın vanası",
        "yangin vanasi",
      ],
      weight: 3,
    },
    {
      terms: [
        "su borusu patlamış",
        "su borusu patlamis",
        "ana boru patlak",
        "şebeke patladı",
        "sebeke patladi",
        "su fışkırıyor yola",
        "su fiskiriyor yola",
        "vana kırıldı su akıyor",
        "vana kirildi su akiyor",
      ],
      weight: 7,
    },
    {
      terms: [
        "3 gündür su yok",
        "uc gundur su yok",
        "haftadır susuz",
        "haftadir susuz",
        "su kesildi gelmedi",
        "duyuru yok su kesik",
        "ani su kesintisi",
        "sadece gece su geliyor",
        "gündüz su yok",
        "gunduz su yok",
        "üst katlar susuz",
        "ust katlar susuz",
      ],
      weight: 6,
    },
    {
      terms: [
        "su tadı bozuk",
        "su tadi bozuk",
        "su kokuyor klor",
        "aşırı klorlu",
        "asiri klorlu",
        "su bulandı",
        "su bulandi",
        "musluktan çamur",
        "musluktan camur",
        "kum geliyor sudan",
        "su sıcak değil depo",
        "su sicak degil",
        "soğuk su gelmiyor",
        "soguk su gelmiyor",
      ],
      weight: 5,
    },
    {
      terms: [
        "sayaç değişsin",
        "sayac degissin",
        "sayaç okuma",
        "sayac okuma",
        "su faturası anormal",
        "su faturasi anormal",
        "kaçak su kullanımı değil arıza",
        "su arıza ihbar",
        "su ariza ihbar",
        "su ve kanal çağrı",
        "su ve kanal cagri",
        "içme suyu şikayeti",
        "icme suyu sikayeti",
      ],
      weight: 4,
    },
    {
      terms: [
        "yangın hidrantı",
        "yangin hidranti",
        "hidrant arızalı",
        "hidrant arizali",
        "sulama suyu karıştı",
        "sulama suyu karisti",
        "şebeke basıncı",
        "sebeke basinci",
      ],
      weight: 3,
    }
  ],

  "Asfalt Onarım": [
    {
      terms: [
        "asfalt",
        "asfalti",
        "asfaltı",
        "asfaltlar",
        "asfalt kaplama",
      ],
      weight: 6,
    },
    {
      terms: [
        "asfalt yama",
        "yamalik",
        "yamalık",
        "yama yapin",
        "yama yapın",
        "yama lazım",
        "yama lazim",
        "yama yapilmamis",
        "yama yapılmamış",
      ],
      weight: 5,
    },
    {
      terms: [
        "asfalt cokmus",
        "asfalt çökmüş",
        "asfalt kaymis",
        "asfalt kaymış",
        "asfalt delik",
        "asfalt yarilmıs",
        "asfalt yarılmış",
        "asfalt catlak",
        "asfalt çatlak",
        "asfalt sokulmus",
        "asfalt sökülmüş",
      ],
      weight: 7,
    },
    {
      terms: [
        "asfalt bozul",
        "asfalt kirik",
        "asfalt kırık",
        "kaplama bozul",
        "kaplama kalkti",
        "kaplama kalktı",
        "sicakta asfalt",
        "sıcakta asfalt",
        "asfalt erimis",
        "asfalt erimiş",
      ],
      weight: 5,
    },
    {
      terms: [
        "asfalt dökülsün",
        "asfalt dokulsun",
        "asfalt yapılsın",
        "asfalt yapilsin",
        "yeniden asfaltlansın",
        "yeniden asfaltlansin",
        "sıcak asfalt",
        "sicak asfalt",
        "soğuk asfalt",
        "soguk asfalt",
        "asfalt makinesi",
        "finişer",
      ],
      weight: 6,
    },
    {
      terms: [
        "asfalt parçalandı",
        "asfalt parcalandi",
        "asfalt kabardı",
        "asfalt kabardi",
        "asfalt dalgalı",
        "asfalt dalgali",
        "asfalt çukurlaştı",
        "asfalt cukurlasti",
        "binder bozuldu",
        "binder kalktı",
        "binder kalkti",
        "asfalt şeridi",
        "asfalt seridi",
      ],
      weight: 5,
    },
    {
      terms: [
        "yama bile yok",
        "geçici yama",
        "gecici yama",
        "yama tutmamış",
        "yama tutmamis",
        "asfalt kenarı açık",
        "asfalt kenari acik",
        "asfalt bitmemiş",
        "asfalt bitmemis",
      ],
      weight: 4,
    },
    {
      terms: [
        "asfalt dökün",
        "asfalt dokun",
        "caddeye asfalt",
        "sokağa asfalt",
        "sokaga asfalt",
        "asfalt yenilensin acil",
        "asfalt tamamen kalkmış",
        "asfalt tamamen kalkmis",
      ],
      weight: 7,
    },
    {
      terms: [
        "asfalt şişmiş",
        "asfalt sismis",
        "asfalt yarık",
        "asfalt yarik",
        "asfalt çukurları",
        "asfalt cukurlari",
        "asfalt yüzeyi bozuk",
        "asfalt yuzeyi bozuk",
        "asfalt kenarı çöktü",
        "asfalt kenari coktu",
        "bitüm kalktı",
        "bitum kalkti",
        "sathi kaplama bozuldu",
      ],
      weight: 5,
    },
    {
      terms: [
        "yama bile tutmadı",
        "yama bile tutmadi",
        "geçici kaplama",
        "gecici kaplama",
        "asfalt ekibi gelsin",
        "asfalt çalışması yarım",
        "asfalt calismasi yarim",
      ],
      weight: 4,
    }
  ],

  "Yol Bozukluğu": [
    {
      terms: [
        "yol cukuru",
        "yol çukuru",
        "buyuk cukur",
        "büyük çukur",
        "derin cukur",
        "derin çukur",
        "dev cukur",
        "dev çukur",
        "tehlikeli cukur",
        "tehlikeli çukur",
      ],
      weight: 7,
    },
    {
      terms: [
        "cukur",
        "çukur",
        "cukurlu yol",
        "çukurlu yol",
        "cukurlu cadde",
        "çukurlu cadde",
        "cukura dustu",
        "çukura düştü",
        "lastik patladi cukur",
        "lastik patladı çukur",
      ],
      weight: 5,
    },
    {
      terms: [
        "yol bozuk",
        "yol cokmus",
        "yol çökmüş",
        "yol kaymis",
        "yol kaymış",
        "yol acilamaz",
        "yol geçilmez",
        "yol gecilmez",
        "yol berbat",
        "yol mahvoldu",
        "cadde bozuk",
        "sokak bozuk",
      ],
      weight: 6,
    },
    {
      terms: [
        "kaldirim",
        "kaldırım",
        "bordur",
        "bordür",
        "kaldirim kirik",
        "kaldırım kırık",
        "kaldirim cokmus",
        "kaldırım çökmüş",
        "yaya yolu bozuk",
        "kaldirim taslari",
        "kaldırım taşları",
      ],
      weight: 5,
    },
    {
      terms: [
        "stabilize",
        "stabilize yol",
        "parke bozul",
        "parke tas",
        "parke taş",
        "parke sokulmus",
        "parke sökülmüş",
        "menfez",
        "kopru yaklasim",
        "köprü yaklaşım",
        "hemzemin",
      ],
      weight: 4,
    },
    {
      terms: [
        "yol",
        "cadde",
        "sokak",
      ],
      weight: 2,
    },
    {
      terms: [
        "araç lastiği patladı çukur",
        "arac lastigi patladi cukur",
        "çukura girdik",
        "cukura girdik",
        "yolda uçurum gibi",
        "yolda ucurum gibi",
        "geçilmez çukur",
        "gecilmez cukur",
        "kaza çıkacak çukur",
        "kaza cikacak cukur",
      ],
      weight: 7,
    },
    {
      terms: [
        "stabilize bozuldu",
        "stabilize yol berbat",
        "toprak yol çamur",
        "toprak yol camur",
        "yol çamur içinde",
        "yol camur icinde",
        "yol toz toprak",
        "yol geçilmiyor",
        "yol gecilmiyor",
        "araç geçemiyor yol",
        "arac gecemiyor yol",
        "ambulans giremiyor yol",
      ],
      weight: 6,
    },
    {
      terms: [
        "kaldırım yok",
        "kaldirim yok",
        "kaldırım engelli",
        "kaldirim engelli",
        "kaldırım işgali değil bozuk",
        "yaya kaldırımsız",
        "yaya kaldirimsiz",
        "bordür devrilmiş",
        "bordur devrilmis",
        "rampa yok engelli",
        "merdiven bozuk dışarı",
      ],
      weight: 5,
    },
    {
      terms: [
        "parke taşları oynuyor",
        "parke taslari oynuyor",
        "parke çöktü",
        "parke coktu",
        "kilitli parke bozuldu",
        "yol kaplaması kalktı",
        "yol kaplamasi kalkti",
        "hemzemin geçit bozuk",
        "hemzemin gecit bozuk",
        "köprü yolu bozuk",
        "kopru yolu bozuk",
      ],
      weight: 4,
    },
    {
      terms: [
        "çukur doldurulsun",
        "cukur doldurulsun",
        "yol onarımı",
        "yol onarimi",
        "cadde onarımı",
        "cadde onarimi",
        "sokak yapılsın",
        "sokak yapilsin",
      ],
      weight: 3,
    },
    {
      terms: [
        "yolda uçurum",
        "yolda ucurum",
        "devasa çukur",
        "devasa cukur",
        "araç hasar gördü çukur",
        "arac hasar gordu cukur",
        "jant eğildi çukur",
        "jant egildi cukur",
        "süspansiyon bozuldu çukur",
      ],
      weight: 7,
    },
    {
      terms: [
        "yol mahvoldu geçilmiyor",
        "yol mahvoldu gecilmiyor",
        "çamur deryası yol",
        "camur deryasi yol",
        "yağmurda geçilmez yol",
        "yagmurda gecilmez yol",
        "stabilize yol bozulmuş",
        "stabilize yol bozulmus",
        "toprak yol berbat",
        "patika yol bozuk",
        "ara sokak geçilmez",
        "ara sokak gecilmez",
      ],
      weight: 6,
    },
    {
      terms: [
        "kaldırım taşları oynak",
        "kaldirim taslari oynak",
        "kaldırım çöktü",
        "kaldirim coktu",
        "yaya yolu yok",
        "engelli rampası yok",
        "engelli rampasi yok",
        "bordür kırık tehlike",
        "bordur kirik tehlike",
        "merdiven basamağı kırık dışarı",
        "merdiven basamagi kirik",
      ],
      weight: 5,
    },
    {
      terms: [
        "parke döşeme bozuldu",
        "parke doseme bozuldu",
        "kilit parke oynuyor",
        "yol onarım talebi",
        "yol onarim talebi",
        "cadde düzenlemesi",
        "cadde duzenlemesi",
        "menfez tıkalı değil yol bozuk",
      ],
      weight: 4,
    }
  ],

  "Çöp Toplama": [
    {
      terms: [
        "cop topla",
        "çöp topla",
        "cop toplanmadi",
        "çöp toplanmadı",
        "cop alinmadi",
        "çöp alınmadı",
        "cop alınmamış",
        "çöp alinmamis",
        "cop gelmedi",
        "çöp gelmedi",
        "gunlerdir cop",
        "günlerdir çöp",
      ],
      weight: 7,
    },
    {
      terms: [
        "cop arabasi",
        "çöp arabası",
        "temizlik arabasi",
        "temizlik arabası",
        "cop kamyonu",
        "çöp kamyonu",
        "cop araci gecmedi",
        "çöp aracı geçmedi",
        "copcular gelmedi",
        "çöpçüler gelmedi",
      ],
      weight: 6,
    },
    {
      terms: [
        "konteyner",
        "container",
        "cop kutusu",
        "çöp kutusu",
        "cop konteyneri",
        "çöp konteyneri",
        "cop bidonu",
        "çöp bidonu",
        "cop tenekesi",
        "çöp tenekesi",
      ],
      weight: 5,
    },
    {
      terms: [
        "cop kokuyor",
        "çöp kokuyor",
        "cop tasmis",
        "çöp taşmış",
        "cop dolu",
        "çöp dolu",
        "cop yigini",
        "çöp yığını",
        "cop dagilmis",
        "çöp dağılmış",
        "cop sokakta",
        "çöp sokakta",
        "cop birikmis",
        "çöp birikmiş",
      ],
      weight: 5,
    },
    {
      terms: [
        "cop",
        "çöp",
        "copu",
        "çöpü",
        "copler",
        "çöpler",
        "cop lar",
        "copumuz",
        "çöpümüz",
        "evsel atik",
        "evsel atık",
      ],
      weight: 3,
    },
    {
      terms: [
        "cadde supur",
        "cadde süpür",
        "sokak supurme",
        "sokak süpürme",
        "supurge gelmedi",
        "süpürge gelmedi",
        "cadde kirli",
        "sokak kirli",
        "cop suzme",
        "çöp süzme",
      ],
      weight: 4,
    },
    {
      terms: [
        "çöpler alınsın",
        "copler alinsin",
        "çöp toplanmıyor",
        "cop toplanmiyor",
        "haftadır çöp",
        "haftadir cop",
        "çöpçü gelmedi",
        "copcu gelmedi",
        "temizlik gelmedi",
        "çöp saati kaçtı",
        "cop saati kacti",
      ],
      weight: 7,
    },
    {
      terms: [
        "moloz çöp gibi",
        "inşaat çöpü",
        "insaat copu",
        "evsel atık alınmadı",
        "evsel atik alinmadi",
        "geri dönüşüm kutusu dolu",
        "geri donusum kutusu dolu",
        "mavi kapak",
        "cam şişe birikmiş",
        "cam sise birikmis",
        "poşetler uçuşuyor",
        "posetler ucusuyor",
      ],
      weight: 6,
    },
    {
      terms: [
        "konteyner yanmış",
        "konteyner yanmis",
        "konteyner kırık",
        "konteyner kirik",
        "konteyner yok",
        "çöp konteyneri eksik",
        "cop konteyneri eksik",
        "konteyner taşmış sokak",
        "fare çöp yüzünden",
        "fare cop yuzunden",
        "kedi köpek çöpleri dağıttı",
      ],
      weight: 5,
    },
    {
      terms: [
        "çöp toplama günü",
        "cop toplama gunu",
        "hangi gün çöp",
        "hangi gun cop",
        "temizlik işçisi",
        "temizlik iscisi",
        "süpürge makinesi gelmedi",
        "supurge makinesi gelmedi",
        "cadde süpürülmemiş",
        "cadde supurulmemis",
        "yapış yapış sokak",
        "yapıs yapis sokak",
      ],
      weight: 4,
    },
    {
      terms: [
        "çöp dökülmüş",
        "cop dokulmus",
        "çöp bırakılmış",
        "cop birakilmis",
        "atık birikmiş",
        "atik birikmis",
        "koku dayanılmaz çöp",
        "koku dayanilmaz cop",
      ],
      weight: 3,
    },
    {
      terms: [
        "çöpler toplanmıyor",
        "copler toplanmiyor",
        "çöp birikti mahalle",
        "cop birikti mahalle",
        "temizlik arabası geçmedi",
        "temizlik arabasi gecmedi",
        "çöp günü gelmedi",
        "cop gunu gelmedi",
      ],
      weight: 7,
    },
    {
      terms: [
        "konteyner taştı her yere",
        "konteyner tasti her yere",
        "çöp kokusu dayanılmaz",
        "cop kokusu dayanilmaz",
        "çöpler dağılmış sokak",
        "copler dagilmis sokak",
        "vahşi depolama",
        "vahsi depolama",
        "çöp döküm alanı değil sokak",
        "izinsiz çöp dökülmüş",
      ],
      weight: 6,
    },
    {
      terms: [
        "organik atık",
        "organik atik",
        "ambalaj atığı",
        "ambalaj atigi",
        "geri dönüşüm alınmıyor",
        "geri donusum alinmiyor",
        "cam konteyneri dolu",
        "kağıt konteyneri dolu",
        "kagit konteyneri",
        "tıbbi atık şüphesi çöp",
        "tibbi atik suphesi",
        "hayvan ölüsü çöp",
        "hayvan olusu cop",
      ],
      weight: 5,
    },
    {
      terms: [
        "çöp konteyneri yerinden oynatılmış",
        "konteyner yerinden",
        "yeni konteyner istiyoruz",
        "çöp bidonu kırık",
        "cop bidonu kirik",
        "poşetler rüzgarda uçuyor",
        "posetler ruzgarda",
        "sokak süpürülmüyor",
        "sokak supurulmuyor",
        "cadde pis",
        "mahalle pis çöp yüzünden",
      ],
      weight: 4,
    }
  ],

  "Park Bakım": [
    {
      terms: [
        "park bakim",
        "park bakım",
        "parkta",
        "cocuk parki",
        "çocuk parkı",
        "oyun parki",
        "oyun parkı",
        "mahalle parki",
        "mahalle parkı",
        "yesil alan bakim",
        "yeşil alan bakım",
      ],
      weight: 5,
    },
    {
      terms: [
        "agac dustu",
        "ağaç düştü",
        "agac devril",
        "ağaç devril",
        "agac kesil",
        "ağaç kesil",
        "agac kirildi",
        "ağaç kırıldı",
        "dal dustu",
        "dal düştü",
        "agac yola dustu",
        "ağaç yola düştü",
      ],
      weight: 6,
    },
    {
      terms: [
        "salincak",
        "salıncak",
        "kaydirak",
        "kaydırak",
        "tahterevalli",
        "park bank",
        "bank kirik",
        "bank kırık",
        "oyun grubu bozuk",
        "park ekipman",
        "cocuk oyun aleti",
      ],
      weight: 5,
    },
    {
      terms: [
        "cim bic",
        "çim biç",
        "cimler uzamis",
        "çimler uzamış",
        "park sulama",
        "cimler bicilmemis",
        "çimler biçilmemiş",
        "otlar uzamis",
        "otlar uzamış",
        "bicilmemis cim",
      ],
      weight: 5,
    },
    {
      terms: [
        "park lamba",
        "park aydinlatma",
        "park aydınlatma",
        "park isik",
        "park ışık",
        "park lambasi yanmiyor",
        "park lambası yanmıyor",
      ],
      weight: 5,
    },
    {
      terms: [
        "agac",
        "ağaç",
        "agaclar",
        "ağaçlar",
        "yesil alan",
        "yeşil alan",
        "fidan",
        "cicek tarh",
        "çiçek tarh",
        "peyzaj",
      ],
      weight: 3,
    },
    {
      terms: [
        "park",
        "bahce",
        "bahçe",
        "bahceler",
        "bahçeler",
      ],
      weight: 2,
    },
    {
      terms: [
        "ağaç budama",
        "agac budama",
        "budama yapılsın",
        "budama yapilsin",
        "kurumuş ağaç",
        "kurumus agac",
        "tehlikeli ağaç",
        "tehlikeli agac",
        "ağaç kökü kaldırımı kaldırdı",
        "agac koku kaldirimi",
        "dal kırık asılı",
        "dal kirik asili",
      ],
      weight: 6,
    },
    {
      terms: [
        "çocuk parkı bozuk",
        "cocuk parki bozuk",
        "oyun aleti kırık",
        "oyun aleti kirik",
        "salıncak zinciri koptu",
        "salincak zinciri koptu",
        "kaydırak kırık",
        "kaydirak kirik",
        "park zemini bozuk",
        "kauçuk zemin yırtık",
        "kaucuk zemin yirtik",
      ],
      weight: 5,
    },
    {
      terms: [
        "çiçekler sulanmıyor",
        "cicekler sulanmiyor",
        "çiçek tarhı bozulmuş",
        "cicek tarhi",
        "çimler biçilsin",
        "cimler bicilsin",
        "otlar biçilsin",
        "otlar bicilsin",
        "park bakımsız",
        "park bakimsiz",
        "yeşil alan kurudu",
        "yesil alan kurudu",
      ],
      weight: 5,
    },
    {
      terms: [
        "park çöp dolu",
        "park cop dolu",
        "park bankları yok",
        "park banklari yok",
        "park çeşmesi bozuk",
        "park cesmesi bozuk",
        "park tuvaleti kapalı",
        "park tuvaleti kapali",
        "spor aleti kırık park",
        "spor aleti kirik park",
        "yürüyüş yolu bozuk park",
      ],
      weight: 4,
    },
    {
      terms: [
        "fidan dikilsin",
        "ağaç dikilsin",
        "agac dikilsin",
        "park yapılsın",
        "park yapilsin",
        "yeşillendirme",
        "yesillendirme",
        "peyzaj bozuk",
        "bahçe bakımı",
        "bahce bakimi",
      ],
      weight: 3,
    },
    {
      terms: [
        "ağaç yola devrildi",
        "agac yola devrildi",
        "dal koptu araç üstüne",
        "dal koptu arac ustune",
        "çocuk parkı tehlikeli",
        "cocuk parki tehlikeli",
        "salıncak düştü",
        "salincak dustu",
      ],
      weight: 7,
    },
    {
      terms: [
        "park bakımsız kalmış",
        "park bakimsiz kalmis",
        "çimler diz boyu",
        "cimler diz boyu",
        "otlar bürümüş parkı",
        "otlar burumus parki",
        "sulama sistemi bozuk park",
        "fıskiye çalışmıyor",
        "fiskiye calismiyor",
        "park çeşmesi akmıyor",
        "park cesmesi akmiyor",
      ],
      weight: 5,
    },
    {
      terms: [
        "bank kırık park",
        "bank kirik park",
        "çöp kutusu yok parkta",
        "cop kutusu yok parkta",
        "park tuvaleti pis",
        "park aydınlatması sönük",
        "park aydinlatmasi sonuk",
        "yürüyüş parkuru bozuk",
        "yuruyus parkuru bozuk",
        "spor aletleri paslı",
        "spor aletleri pasli",
      ],
      weight: 5,
    },
    {
      terms: [
        "ağaç budansın",
        "agac budansin",
        "kuruyan ağaç kesilsin",
        "kuruyan agac kesilsin",
        "fidanlar sulanmıyor",
        "fidanlar sulanmiyor",
        "çiçekler soldu",
        "cicekler soldu",
        "yeşil alan talebi",
        "yesil alan talebi",
        "park yapılsın mahalleye",
        "park yapilsin mahalleye",
      ],
      weight: 4,
    }
  ],

  "Zabıta Şikayeti": [
    {
      terms: [
        "zabita",
        "zabıta",
        "zabita gelsin",
        "zabıta gelsin",
        "zabita cagirin",
        "zabıta çağırın",
        "zabita ekibi",
        "zabıta ekibi",
      ],
      weight: 6,
    },
    {
      terms: [
        "gurultu",
        "gürültü",
        "ses kirliligi",
        "ses kirliliği",
        "yuksek ses",
        "yüksek ses",
        "gurultu yapıyorlar",
        "gürültü yapıyorlar",
        "rahatsiz ediyor ses",
        "rahatsız ediyor ses",
      ],
      weight: 5,
    },
    {
      terms: [
        "gece muzik",
        "gece müzik",
        "muzik basiyor",
        "müzik basıyor",
        "eglence gurultu",
        "eğlence gürültü",
        "dugun sesi",
        "düğün sesi",
        "kahvehane gurultu",
        "gece 2de muzik",
      ],
      weight: 5,
    },
    {
      terms: [
        "seyyar",
        "seyyar satici",
        "seyyar satıcı",
        "isgal",
        "işgal",
        "tezgah isgal",
        "tezgâh işgal",
        "kaldirim isgal",
        "kaldırım işgal",
        "yol kapatmis seyyar",
        "pazar yeri isgal",
      ],
      weight: 5,
    },
    {
      terms: [
        "kopek saldiri",
        "köpek saldırı",
        "basibos kopek",
        "başıboş köpek",
        "sahipsiz kopek",
        "sahipsiz köpek",
        "kopek isirdi",
        "köpek ısırdı",
        "kopek surusu",
        "köpek sürüsü",
        "tehlike kopek",
      ],
      weight: 5,
    },
    {
      terms: [
        "izinsiz insaat",
        "izinsiz inşaat",
        "kacak yapi",
        "kaçak yapı",
        "isgaliye",
        "isgaliye",
        "izinsiz kazi",
        "izinsiz kazı",
        "moloz dokmus",
        "moloz dökmüş",
        "insaat artiklari yol",
      ],
      weight: 4,
    },
    {
      terms: [
        "kopek",
        "köpek",
        "basibos",
        "başıboş",
        "hayvan saldiri",
        "hayvan saldırı",
        "kedi kopek bakimsiz",
      ],
      weight: 3,
    },
    {
      terms: [
        "zabıta müdahale",
        "zabita mudahale",
        "zabıta kontrol",
        "zabita kontrol",
        "denetim yapılsın",
        "denetim yapilsin",
        "zabıtaya şikayet",
        "zabitaya sikayet",
      ],
      weight: 6,
    },
    {
      terms: [
        "gece yarısı gürültü",
        "gece yarisi gurultu",
        "hoparlör basıyor",
        "hoparlor basiyor",
        "düğün konvoyu ses",
        "dugun konvoyu ses",
        "ekmek arabası korna",
        "ekmek arabasi korna",
        "işyeri sesi rahatsız",
        "isyeri sesi rahatsiz",
        "inşaat gürültüsü gece",
        "insaat gurultusu gece",
      ],
      weight: 5,
    },
    {
      terms: [
        "kaldırım işgali tezgah",
        "kaldirim isgali tezgah",
        "masa sandalye kaldırım",
        "masa sandalye kaldirim",
        "işportacı",
        "isportaci",
        "seyyarlar yol kapattı",
        "seyyarlar yol kapatti",
        "pazar taştı yola",
        "pazar tasti yola",
      ],
      weight: 5,
    },
    {
      terms: [
        "başıboş hayvan",
        "basibos hayvan",
        "köpek sürüsü saldırdı",
        "kopek surusu saldirdi",
        "kuduz riski köpek",
        "kuduz riski kopek",
        "köpek bağlanmamış",
        "kopek baglanmamis",
        "hayvan barınağı",
        "hayvan barinagi",
      ],
      weight: 5,
    },
    {
      terms: [
        "kaçak kat",
        "kacak kat",
        "izinsiz tadilat",
        "ruhsatsız yapı",
        "ruhsatsiz yapi",
        "moloz yola dökülmüş",
        "moloz yola dokulmus",
        "hafriyat dökmüş",
        "hafriyat dokmus",
        "çevre kirliliği işletme",
        "cevre kirliligi isletme",
        "duman rahatsız",
        "duman rahatsiz",
      ],
      weight: 4,
    },
    {
      terms: [
        "işgal kaldırımı",
        "isgal kaldirimi",
        "engel oluşturuyor",
        "engel olusturuyor",
        "trafik engeli seyyar",
        "yasa dışı satış",
        "yasa disi satis",
      ],
      weight: 3,
    },
    {
      terms: [
        "zabıta acil gelsin",
        "zabita acil gelsin",
        "gece gürültü dayanılmaz",
        "gece gurultu dayanilmaz",
        "köpek ısırdı çocuk",
        "kopek isirdi cocuk",
        "seyyar yol kapattı acil",
        "seyyar yol kapatti acil",
      ],
      weight: 7,
    },
    {
      terms: [
        "kahvehane gürültüsü",
        "kahvehane gurultusu",
        "nargile dumanı",
        "nargile dumani",
        "işyeri hoparlör",
        "isyeri hoparlor",
        "gece 3'te müzik",
        "gece 3te muzik",
        "düğün salonu sesi",
        "dugun salonu sesi",
        "konvoy korna",
        "ekmekçi korna gece",
      ],
      weight: 5,
    },
    {
      terms: [
        "kaldırım işgali masa",
        "kaldirim isgali masa",
        "tezgah yola taşmış",
        "tezgah yola tasmıs",
        "seyyar satıcı engel",
        "seyyar satici engel",
        "işportacılar",
        "isportacilar",
        "pazar kurulumu yola taştı",
        "pazar kurulumu yola tasti",
      ],
      weight: 5,
    },
    {
      terms: [
        "başıboş köpek sürüsü",
        "basibos kopek surusu",
        "saldırgan köpek",
        "saldirgan kopek",
        "köpek bağlanmıyor",
        "kopek baglanmiyor",
        "mama yeri koku zabıta",
        "hayvan şikayeti zabıta",
      ],
      weight: 5,
    },
    {
      terms: [
        "kaçak inşaat",
        "kacak insaat",
        "ruhsatsız tadilat",
        "ruhsatsiz tadilat",
        "moloz kaldırımda",
        "moloz kaldirimda",
        "hafriyat yola dökülmüş",
        "hafriyat yola dokulmus",
        "çevre kirliliği duman",
        "cevre kirliligi duman",
        "kötü koku işletme",
        "kotu koku isletme",
      ],
      weight: 4,
    }
  ],

  "Ulaşım Sorunu": [
    {
      terms: [
        "otobus gelmiyor",
        "otobüs gelmiyor",
        "otobus gecikti",
        "otobüs gecikti",
        "otobus yok",
        "otobüs yok",
        "otobus gecmiyor",
        "otobüs geçmiyor",
        "otobus saatlerce gelmedi",
        "sabah otobus yok",
      ],
      weight: 7,
    },
    {
      terms: [
        "otobus",
        "otobüs",
        "minibus",
        "minibüs",
        "ring otobus",
        "ring otobüs",
        "belediye otobusu",
        "belediye otobüsü",
        "halk otobusu",
        "dolmus",
        "dolmuş",
      ],
      weight: 5,
    },
    {
      terms: [
        "durak bozuk",
        "durak yok",
        "otobus duragi",
        "otobüs durağı",
        "durak camı kırık",
        "durak cami kirik",
        "durakta oturacak yer yok",
        "durak isik yok",
      ],
      weight: 5,
    },
    {
      terms: [
        "guzergah",
        "güzergah",
        "hat degisti",
        "hat değişti",
        "sefer iptal",
        "sefer azaldi",
        "sefer azaldı",
        "hat numarasi",
        "yanlis hat",
        "yanlış hat",
      ],
      weight: 4,
    },
    {
      terms: [
        "ulasim",
        "ulaşım",
        "toplu tasima",
        "toplu taşıma",
        "belediye otobus",
        "kart basmiyor",
        "kentkart",
        "ulasim karti",
      ],
      weight: 3,
    },
    {
      terms: [
        "ring",
        "sefer",
        "hat",
      ],
      weight: 2,
    },
    {
      terms: [
        "otobüs geçmiyor mahalleye",
        "otobus gecmiyor mahalleye",
        "hat kaldırılmış",
        "hat kaldirilmis",
        "sefer yok sabah",
        "akşam otobüs yok",
        "aksam otobus yok",
        "işe yetişemiyorum otobüs",
        "ise yetisemiyorum otobus",
      ],
      weight: 7,
    },
    {
      terms: [
        "şoför kaba",
        "sofor kaba",
        "şoför durakta durmadı",
        "sofor durakta durmadi",
        "kapı arızalı otobüs",
        "kapi arizali otobus",
        "klima yok otobüs",
        "klima yok otobus",
        "otobüs aşırı kalabalık",
        "otobus asiri kalabalik",
        "ayakta gidiyoruz",
      ],
      weight: 5,
    },
    {
      terms: [
        "durak tabelası yok",
        "durak tabelasi yok",
        "durak kaymış",
        "durak kaymis",
        "durak yeri değişmiş",
        "durak yeri degismis",
        "durak aydınlatması yok",
        "durak aydinlatmasi yok",
        "otobüs saati uyumsuz",
        "otobus saati uyumsuz",
        "zaman çizelgesi yanlış",
      ],
      weight: 5,
    },
    {
      terms: [
        "kent kart basmıyor",
        "kent kart basmiyor",
        "kart okumuyor",
        "bakiye yüklenmiyor",
        "bakiye yuklenmiyor",
        "ücretsiz geçiş sorunu",
        "ucretsiz gecis sorunu",
        "öğrenci kartı",
        "ogrenci karti",
        "65 yaş kart",
        "65 yas kart",
      ],
      weight: 4,
    },
    {
      terms: [
        "toplu taşıma şikayeti",
        "toplu tasima sikayeti",
        "hat önerisi",
        "hat onerisi",
        "yeni hat talebi",
        "sefer artsın",
        "sefer artsin",
        "ring yetersiz",
      ],
      weight: 3,
    },
    {
      terms: [
        "otobüs hiç gelmiyor",
        "otobus hic gelmiyor",
        "saatlerdir otobüs yok",
        "saatlerdir otobus yok",
        "hat iptal edilmiş",
        "hat iptal edilmis",
        "ring çalışmıyor",
        "ring calismiyor",
      ],
      weight: 7,
    },
    {
      terms: [
        "şoför durmadı",
        "sofor durmadi",
        "kapıyı açmadı",
        "kapiyi acmadi",
        "erken kalktı duraktan",
        "erken kalkti duraktan",
        "otobüs rötarlı",
        "otobus rotarli",
        "sefer aksadı",
        "sefer aksadi",
      ],
      weight: 5,
    },
    {
      terms: [
        "durak yıkık",
        "durak yikik",
        "durak camı yok",
        "durak cami yok",
        "durak iskemlesi kırık",
        "durak iskemlesi kirik",
        "yanlış durakta indi",
        "yanlis durakta indi",
        "hat yazısı yok",
      ],
      weight: 5,
    },
    {
      terms: [
        "kentkart çalışmıyor",
        "kentkart calismiyor",
        "kart basmadı",
        "kart basmadi",
        "bakiye düştü gitmedi",
        "bakiye dustu gitmedi",
        "öğrenci indirimi uygulanmadı",
        "ogrenci indirimi uygulanmadi",
        "ücretsiz geçiş tanınmadı",
        "ucretsiz gecis taninmadi",
      ],
      weight: 4,
    },
    {
      terms: [
        "yeni sefer talebi",
        "gece seferi olsun",
        "hafta sonu sefer artsın",
        "hafta sonu sefer artsin",
        "güzergah uzatılsın",
        "guzergah uzatilsin",
        "durak eklensin",
        "minibus hattı",
        "minibus hatti",
      ],
      weight: 3,
    }
  ],

  "Diğer": [
    {
      terms: [
        "kar temiz",
        "kar kureme",
        "kar küreme",
        "kar kure",
        "kar küre",
        "buzlanma",
        "buz tutmus",
        "buz tutmuş",
        "kar temizligi yapilmadi",
        "kar temizliği yapılmadı",
        "yol buzlu",
        "kalkaniyor buz",
      ],
      weight: 5,
    },
    {
      terms: [
        "sokak lamba",
        "sokak lambasi",
        "sokak lambası",
        "direk lamba",
        "aydinlatma yanmiyor",
        "aydınlatma yanmıyor",
        "lamba yanmiyor",
        "lamba yanmıyor",
        "karanlik sokak",
        "karanlık sokak",
        "isik yok sokak",
        "ışık yok sokak",
      ],
      weight: 4,
    },
    {
      terms: [
        "trafik isareti",
        "trafik işareti",
        "levha dusmus",
        "levha düşmüş",
        "trafik lambasi",
        "trafik lambası",
        "isiklar arizali",
        "ışıklar arızalı",
      ],
      weight: 4,
    },
    {
      terms: [
        "genel sikayet",
        "genel şikayet",
        "bilmiyorum hangi",
        "diger konu",
        "diğer konu",
        "baska bir sorun",
        "başka bir sorun",
      ],
      weight: 2,
    },
    {
      terms: [
        "kar küreme aracı gelsin",
        "kar kureme araci gelsin",
        "tuzlama yapılsın",
        "tuzlama yapilsin",
        "buz çözülsün",
        "buz cozulsun",
        "kar yığınları",
        "kar yiginlari",
        "kaldırımda kar",
        "kaldirimda kar",
        "araçlar kayıyor buz",
        "araclar kayiyor buz",
      ],
      weight: 5,
    },
    {
      terms: [
        "aydınlatma direği eğik",
        "aydinlatma diregi egik",
        "lamba kırık",
        "lamba kirik",
        "projektör yanmıyor",
        "projektor yanmiyor",
        "park dışı sokak ışığı",
        "park disi sokak isigi",
        "karanlık mahalle",
        "karanlik mahalle",
        "gece göremiyoruz",
        "gece goremiyoruz",
      ],
      weight: 4,
    },
    {
      terms: [
        "trafik levhası yok",
        "trafik levhasi yok",
        "dur levhası düşmüş",
        "dur levhasi dusmus",
        "hız limiti tabelası",
        "hiz limiti tabelasi",
        "trafik ışığı arızalı",
        "trafik isigi arizali",
        "kırmızı ışık yanmıyor",
        "kirmizi isik yanmiyor",
        "yaya geçidi boyası silinmiş",
      ],
      weight: 4,
    },
    {
      terms: [
        "çevre düzenlemesi",
        "cevre duzenlemesi",
        "genel düzen",
        "genel duzen",
        "belediyeye öneri",
        "belediyeye oneri",
        "bilmiyorum kime",
        "yanlış birime düşmesin",
        "yanlis birime dusmesin",
        "diğer talep",
        "diger talep",
      ],
      weight: 3,
    },
    {
      terms: [
        "kar küreme gelmedi",
        "kar kureme gelmedi",
        "yol buz pist gibi",
        "kaldırım buz",
        "kaldirim buz",
        "tuz serpilmedi",
        "kar yığınları ortada",
        "kar yiginlari ortada",
      ],
      weight: 6,
    },
    {
      terms: [
        "sokak lambası sönük",
        "sokak lambasi sonuk",
        "birkaç lamba yanmıyor",
        "birkac lamba yanmiyor",
        "aydınlatma yetersiz",
        "aydinlatma yetersiz",
        "direk devrilmek üzere",
        "direk devrilmek uzere",
        "kablo sarkıyor lamba",
        "kablo sarkiyor lamba",
      ],
      weight: 5,
    },
    {
      terms: [
        "trafik tabelası yok",
        "trafik tabelasi yok",
        "yön levhası düşmüş",
        "yon levhasi dusmus",
        "hız kesici boyası silinmiş",
        "hiz kesici boyasi",
        "yaya geçidi belirsiz",
        "yaya gecidi belirsiz",
        "trafik ışığı yanıp sönüyor",
        "trafik isigi yanip sonuyor",
      ],
      weight: 4,
    },
    {
      terms: [
        "çevre düzeni",
        "cevre duzeni",
        "şehir estetiği",
        "sehir estetigi",
        "genel şikayet belediye",
        "genel sikayet belediye",
        "hangi birime bilmiyorum",
        "yanlış yönlendirmeyin",
        "yanlis yonlendirmeyin",
      ],
      weight: 3,
    }
  ]
};

export const DEPARTMENT_BY_TUR: Record<string, string> = Object.fromEntries(
  SIKAYET_TURLERI.map((t) => [t.name, t.defaultDepartment]),
);

export const INTENT_LEXICON: Record<"durum_sorgu" | "tesekkur" | "bilgi_talebi", LexGroup[]> = {
  durum_sorgu: [
    {
      terms: [
        "durum",
        "ne oldu",
        "takip",
        "sonuc",
        "sonuç",
        "ne durumda",
        "ne asamada",
        "ne aşamada",
        "guncelleme",
        "güncelleme",
      ],
      weight: 4,
    },
    {
      terms: [
        "sikayet no",
        "şikayet no",
        "sky-",
        "sky ",
        "basvuru",
        "başvuru",
        "basvuru no",
        "başvuru no",
        "kayit no",
        "kayıt no",
        "referans no",
      ],
      weight: 5,
    },
    {
      terms: [
        "asamada",
        "aşamada",
        "ne zaman cozul",
        "ne zaman çözül",
        "ekipler ne zaman",
        "ne zaman gelecek",
        "ne zaman bakacaklar",
        "islem yapildi mi",
        "işlem yapıldı mı",
        "sonuclandi mi",
        "sonuçlandı mı",
      ],
      weight: 4,
    },
    {
      terms: [
        "kayit var mi",
        "kayıt var mı",
        "numaramla",
        "telefonumla kayit",
        "acik sikayetim",
        "açık şikayetim",
        "bekleyen basvuru",
        "bekleyen başvuru",
      ],
      weight: 4,
    },
    {
      terms: [
        "şikayetim ne oldu",
        "sikayetim ne oldu",
        "başvurum sonuçlandı mı",
        "basvurum sonuclandi mi",
        "işlem durumu",
        "islem durumu",
        "dosya numarası",
        "dosya numarasi",
        "takip numarası",
        "takip numarasi",
        "ne zaman bitecek",
        "kaç gündür bekliyorum",
        "kac gundur bekliyorum",
      ],
      weight: 5,
    },
    {
      terms: [
        "güncel durum",
        "guncel durum",
        "son durum nedir",
        "cevap var mı",
        "cevap var mi",
        "dönüş yapıldı mı",
        "donus yapildi mi",
        "baktınız mı şikayetime",
        "baktiniz mi sikayetime",
      ],
      weight: 4,
    },
    {
      terms: [
        "şikayetimin durumu",
        "sikayetimin durumu",
        "başvuru sonucu",
        "basvuru sonucu",
        "ne zaman sonuçlanır",
        "ne zaman sonuclanir",
        "ekip geldi mi",
        "bakıldı mı şikayetime",
        "bakildi mi sikayetime",
        "açık kaydım var mı",
        "acik kaydim var mi",
      ],
      weight: 5,
    },
    {
      terms: [
        "takip etmek istiyorum",
        "güncelleme isterim",
        "guncelleme isterim",
        "son gelişme nedir",
        "son gelisme nedir",
        "cevap bekliyorum",
        "geri dönüş yok",
        "geri donus yok",
      ],
      weight: 4,
    }
  ],
  tesekkur: [
    {
      terms: [
        "tesekkur",
        "teşekkür",
        "tesekkurler",
        "teşekkürler",
        "sagol",
        "sağol",
        "sagolun",
        "sağolun",
        "eyvallah",
        "tsekkur",
      ],
      weight: 5,
    },
    {
      terms: [
        "allah razi",
        "allah razı",
        "memnun kaldim",
        "memnun kaldım",
        "ilgilendiniz",
        "ilgilendiniz icin",
        "yardimci oldunuz",
        "yardımcı oldunuz",
        "cok iyi oldu",
        "çok iyi oldu",
      ],
      weight: 4,
    },
    {
      terms: [
        "ok tesekkur",
        "ok teşekkür",
        "cok sagol",
        "çok sağol",
        "tamam tesekkur",
        "tamam teşekkür",
        "rika ederim degil sagol",
      ],
      weight: 5,
    },
    {
      terms: [
        "teşekkür ederim",
        "tesekkur ederim",
        "çok teşekkür",
        "cok tesekkur",
        "sağ olun",
        "sag olun",
        "elinize sağlık",
        "elinize saglik",
        "allah razı olsun hepinizden",
      ],
      weight: 5,
    },
    {
      terms: [
        "sorun çözüldü teşekkür",
        "sorun cozuldu tesekkur",
        "gelip baktılar sağol",
        "gelip baktilar sagol",
        "memnuniyet",
        "teşekkür mesajı",
        "tesekkur mesaji",
      ],
      weight: 4,
    },
    {
      terms: [
        "çok sağ olun",
        "cok sag olun",
        "teşekkürler ilgiden",
        "tesekkurler ilgiden",
        "sorunu çözdünüz",
        "sorunu cozdunuz",
        "memnun kaldık",
        "memnun kaldik",
        "eyvallah kardeşim",
      ],
      weight: 5,
    },
    {
      terms: [
        "rica ederim değil teşekkür",
        "ok sağol",
        "ok sagol",
        "tm teşekkür",
        "tm tesekkur",
        "👍",
      ],
      weight: 3,
    }
  ],
  bilgi_talebi: [
    {
      terms: [
        "bilgi",
        "nasil",
        "nasıl",
        "nereye basvur",
        "nereye başvur",
        "nasil yapilir",
        "nasıl yapılır",
        "bilgi almak",
        "ogrenmek istiyorum",
        "öğrenmek istiyorum",
      ],
      weight: 4,
    },
    {
      terms: [
        "calisma saat",
        "çalışma saat",
        "telefon numar",
        "randevu",
        "abonelik",
        "adres nedir",
        "hangi saat",
        "mesai saat",
        "iletisim",
        "iletişim",
      ],
      weight: 4,
    },
    {
      terms: [
        "imza gunu",
        "imza günü",
        "hangi birim",
        "hangi mudurluk",
        "hangi müdürlük",
        "nereye dilekce",
        "nereye dilekçe",
        "basvuru sartlari",
        "başvuru şartları",
        "gerekli evrak",
      ],
      weight: 4,
    },
    {
      terms: [
        "nasıl başvurabilirim",
        "nasil basvurabilirim",
        "hangi evraklar",
        "gerekli belgeler",
        "ücret ne kadar",
        "ucret ne kadar",
        "nereden alınır",
        "nereden alinir",
        "online başvuru var mı",
        "online basvuru var mi",
      ],
      weight: 5,
    },
    {
      terms: [
        "belediye adresi",
        "başvuru saatleri",
        "basvuru saatleri",
        "nöbetçi birim",
        "nobetci birim",
        "hangi müdürlük bakar",
        "hangi mudurluk bakar",
        "bilgi istiyorum",
        "danışmak istiyorum",
        "danismak istiyorum",
        "açıklama yapar mısınız",
        "aciklama yapar misiniz",
      ],
      weight: 4,
    },
    {
      terms: [
        "nasıl dilekçe veririm",
        "nasil dilekce veririm",
        "başvuru formu nerede",
        "basvuru formu nerede",
        "hangi belgeler lazım",
        "ücret tarifesi",
        "ucret tarifesi",
        "randevu nasıl alınır",
        "randevu nasil alinir",
        "çalışma günleri",
        "calisma gunleri",
      ],
      weight: 5,
    },
    {
      terms: [
        "belediye telefon",
        "alo belediye",
        "çağrı merkezi numarası",
        "cagri merkezi numarasi",
        "e-belediye",
        "online işlem",
        "online islem",
        "nereden öğrenebilirim",
        "nereden ogrenebilirim",
        "bilgi verir misiniz",
      ],
      weight: 4,
    }
  ]
};

export const ONCELIK_LEXICON = {
  COK_ACIL: [
    {
      terms: [
        "cok acil",
        "çok acil",
        "super acil",
        "süper acil",
        "acil acil",
        "tehlike",
        "hayati",
        "hayati tehlike",
        "hayati risk",
        "olum tehlikesi",
        "ölüm tehlikesi",
      ],
      weight: 5,
    },
    {
      terms: [
        "eve giriyor",
        "eve girdi",
        "sokak su icinde",
        "sokak su içinde",
        "devrilmis",
        "devrilmiş",
        "cocuk dustu",
        "çocuk düştü",
        "arac dustu cukur",
        "araç düştü çukur",
        "yol kapandi tamamen",
        "yol kapandı tamamen",
      ],
      weight: 5,
    },
    {
      terms: [
        "fiskiriyor",
        "fışkırıyor",
        "patladi",
        "patladı",
        "tasdi",
        "taştı",
        "baski yapıyor",
        "baskı yapıyor",
        "kontrol edilemiyor",
      ],
      weight: 4,
    },
    {
      terms: [
        "acil müdahale",
        "acil mudahale",
        "hemen gelsinler",
        "can tehlikesi",
        "yaralanma riski",
        "çocuklar tehlikede",
        "cocuklar tehlikede",
        "yaşlılar düşecek",
        "yaslilar dusecek",
        "sokak tamamen kapalı",
        "sokak tamamen kapali",
        "su basıyor evi",
        "su basiyor evi",
      ],
      weight: 5,
    },
    {
      terms: [
        "çok acil müdahale",
        "cok acil mudahale",
        "hayati tehlike var",
        "acil ekipler gelsin",
        "bekleyemeyiz tehlike",
        "hemen şimdi",
        "hemen simdi",
        "afet gibi durum",
      ],
      weight: 6,
    }
  ] as LexGroup[],
  ACIL: [
    {
      terms: [
        "acil",
        "hemen",
        "yardim edin",
        "yardım edin",
        "lutfen acil",
        "lütfen acil",
        "biran once",
        "biran önce",
        "acele",
      ],
      weight: 4,
    },
    {
      terms: [
        "cok kotu",
        "çok kötü",
        "saldiri",
        "saldırı",
        "dusebilir",
        "düşebilir",
        "tehlike var",
        "riskli",
        "kaza olabilir",
        "gecilemiyor",
        "geçilemiyor",
      ],
      weight: 3,
    },
    {
      terms: [
        "öncelikli",
        "oncelikli",
        "ivedi",
        "acele edin",
        "bekleyemeyiz",
        "bugün bakılsın",
        "bugun bakilsin",
        "yarın olmaz bugün",
        "yarin olmaz bugun",
        "mağduruz",
        "magduruz",
      ],
      weight: 4,
    },
    {
      terms: [
        "öncelik verin",
        "oncelik verin",
        "ivedilikle",
        "acele bakılsın",
        "acele bakilsin",
        "bugün çözülsün",
        "bugun cozulsun",
        "mağduriyet büyüyor",
        "magduriyet buyuyor",
      ],
      weight: 4,
    }
  ] as LexGroup[],
};

/** Canonical mahalle → folded aliases (longest match preferred). */
export const MAHALLE_ALIASES: Array<{
  name: (typeof MAHALLELER)[number];
  aliases: string[];
}> = [
  {
    name: "30 Ekim Mahallesi",
    aliases: [
          "30 ekim mahallesi",
          "30 ekim mah",
          "30 ekim",
          "30ekim",
          "otuz ekim",
          "30ekim mah",
          "otuzekim",
          "30 ekimde",
          "30 ekim mahallesinde",
          "otuz ekim mahallesi",
          "30ekimde"
    ],
  },
  {
    name: "Fevzi Çakmak Mahallesi",
    aliases: [
          "fevzi cakmak mahallesi",
          "fevzi çakmak mahallesi",
          "fevzi cakmak mah",
          "fevzi cakmak",
          "fevzi çakmak",
          "fevziçakmak",
          "f cakmak",
          "fevzi",
          "f.çakmak",
          "f.cakmak",
          "çakmak mah",
          "cakmak mah",
          "fevzi çakmak mahallesinde",
          "fevzi cakmak mahallesinde",
          "çakmak mahallesi"
    ],
  },
  {
    name: "Aydınlıkevler Mahallesi",
    aliases: [
          "aydinlikevler mahallesi",
          "aydınlıkevler mahallesi",
          "aydinlikevler mah",
          "aydinlikevler",
          "aydınlıkevler",
          "aydinli evler",
          "aydınlıkevlerde",
          "aydinlikevlerde",
          "aydınlıkevler mahallesinde",
          "aydinlikevler mahallesinde"
    ],
  },
  {
    name: "Bahçelievler Mahallesi",
    aliases: [
          "bahcelievler mahallesi",
          "bahçelievler mahallesi",
          "bahcelievler mah",
          "bahcelievler",
          "bahçelievler",
          "bahceli evler",
          "bahçeli",
          "bahceli",
          "b.evler",
          "bahcelievlerde",
          "bahçelievler mahallesinde",
          "bahcelievler mahallesinde",
          "b.evler mh"
    ],
  },
  {
    name: "Yenişehir Mahallesi",
    aliases: [
          "yenisehir mahallesi",
          "yenişehir mahallesi",
          "yenisehir mah",
          "yenişehir mah",
          "yenisehir",
          "yenişehir",
          "yeni sehir",
          "ynshr",
          "yeni şehir mah",
          "yenisehirde",
          "yenişehirde",
          "yenisehirden",
          "yenisehir mh",
          "yenişehir mh",
          "y.şehir",
          "y.sehir",
          "yenisehirden yazıyorum"
    ],
  },
  {
    name: "Cumhuriyet Mahallesi",
    aliases: [
          "cumhuriyet mahallesi",
          "cumhuriyet mah",
          "cumhuriyet",
          "c.mahalle",
          "cumhuriyette",
          "cumhuriyetten",
          "cumhuriyet mh",
          "c.mh",
          "cumhuriyet mahallesinde",
          "cumh. mah",
          "cumhuriyetteyiz"
    ],
  },
  {
    name: "Atatürk Mahallesi",
    aliases: [
          "ataturk mahallesi",
          "atatürk mahallesi",
          "ataturk mah",
          "atatürk mah",
          "ataturk",
          "atatürk",
          "ata turk",
          "ataturkde",
          "atatürkde",
          "ataturkten",
          "ata mahalle",
          "ataturk mh",
          "ataturkten yazıyorum",
          "ata mh",
          "atatürkten",
          "ataturk mahallesinde"
    ],
  },
  {
    name: "Halitpaşa Mahallesi",
    aliases: [
          "halitpasa mahallesi",
          "halitpaşa mahallesi",
          "halitpasa mah",
          "halitpasa",
          "halitpaşa",
          "halit pasa",
          "halitpaşada",
          "halitpasada",
          "halitpaşa mahallesinde",
          "halitpasa mahallesinde"
    ],
  },
  {
    name: "Hafızpaşa Mahallesi",
    aliases: [
          "hafizpasa mahallesi",
          "hafızpaşa mahallesi",
          "hafizpasa mah",
          "hafizpasa",
          "hafızpaşa",
          "hafiz pasa",
          "hafızpaşada",
          "hafizpasada",
          "hafızpaşa mahallesinde",
          "hafizpasa mahallesinde"
    ],
  },
  {
    name: "Bayrampaşa Mahallesi",
    aliases: [
          "bayrampasa mahallesi",
          "bayrampaşa mahallesi",
          "bayrampasa mah",
          "bayrampasa",
          "bayrampaşa",
          "bayram pasa",
          "bayrampaşada",
          "bayrampasada",
          "bayrampaşa mahallesinde",
          "bayrampasa mahallesinde"
    ],
  },
  {
    name: "Yusufpaşa Mahallesi",
    aliases: [
          "yusufpasa mahallesi",
          "yusufpaşa mahallesi",
          "yusufpasa mah",
          "yusufpasa",
          "yusufpaşa",
          "yusuf pasa",
          "yusufpaşada",
          "yusufpasada",
          "yusufpaşa mahallesinde",
          "yusufpasa mahallesinde"
    ],
  },
  {
    name: "Paşaçayır Mahallesi",
    aliases: [
          "pasacayir mahallesi",
          "paşaçayır mahallesi",
          "pasacayir mah",
          "pasacayir",
          "paşaçayır",
          "pasa cayir",
          "paşa çayır",
          "paşaçayırda",
          "pasacayirda",
          "paşaçayır mahallesinde",
          "pasacayir mahallesinde"
    ],
  },
  {
    name: "Ortakapı Mahallesi",
    aliases: [
          "ortakapi mahallesi",
          "ortakapı mahallesi",
          "ortakapi mah",
          "ortakapi",
          "ortakapı",
          "orta kapi",
          "ortakapıda",
          "ortakapida",
          "orta kapıda",
          "ortakapı mahallesinde",
          "ortakapi mahallesinde",
          "orta kapı mh"
    ],
  },
  {
    name: "Sukapı Mahallesi",
    aliases: [
          "sukapi mahallesi",
          "sukapı mahallesi",
          "sukapi mah",
          "sukapi",
          "sukapı",
          "su kapi",
          "su kapı",
          "sukapıda",
          "sukapida",
          "su kapıda",
          "sukapı mahallesinde",
          "sukapi mahallesinde",
          "su kapı mh"
    ],
  },
  {
    name: "İstasyon Mahallesi",
    aliases: [
          "istasyon mahallesi",
          "istasyon mah",
          "istasyon",
          "gar mahallesi",
          "istasyon civari",
          "gar civarı",
          "gar civari",
          "istasyonda",
          "tren garı",
          "tren gari",
          "istasyon mahallesinde",
          "gar yanı",
          "gar yani",
          "istasyon bölgesi"
    ],
  },
  {
    name: "Alpaslan Mahallesi",
    aliases: [
          "alpaslan mahallesi",
          "alpaslan mah",
          "alpaslan",
          "alp aslan",
          "alpaslanda",
          "alpaslan mh",
          "alpaslan mahallesinde",
          "alpaslan'da",
          "alpaslanda oturuyorum"
    ],
  },
  {
    name: "Kaleiçi Mahallesi",
    aliases: [
          "kaleici mahallesi",
          "kaleiçi mahallesi",
          "kaleici mah",
          "kaleici",
          "kaleiçi",
          "kale ici",
          "kale içi",
          "kale içinde",
          "kale icinde",
          "eski şehir",
          "eski sehir",
          "kalealtı",
          "kalealti",
          "kaleiçi mahallesinde",
          "kaleici mahallesinde",
          "suriçi",
          "surici"
    ],
  },
  {
    name: "Karadağ Mahallesi",
    aliases: [
          "karadag mahallesi",
          "karadağ mahallesi",
          "karadag mah",
          "karadag",
          "karadağ",
          "kara dag",
          "karadağda",
          "karadagda",
          "karadağ mahallesinde",
          "karadag mahallesinde",
          "kara dağ mh"
    ],
  },
  {
    name: "Şehitler Mahallesi",
    aliases: [
          "sehitler mahallesi",
          "şehitler mahallesi",
          "sehitler mah",
          "sehitler",
          "şehitler",
          "şehitlerde",
          "sehitlerde",
          "şehitler mahallesinde",
          "sehitler mahallesinde"
    ],
  },
  {
    name: "Örenek Mahallesi",
    aliases: [
          "orenek mahallesi",
          "örenek mahallesi",
          "orenek mah",
          "orenek",
          "örenek",
          "örenekte",
          "orenekte",
          "örenek mahallesinde",
          "orenek mahallesinde"
    ],
  },
  {
    name: "Bülbül Mahallesi",
    aliases: [
          "bulbul mahallesi",
          "bülbül mahallesi",
          "bulbul mah",
          "bulbul",
          "bülbül",
          "bülbülde",
          "bulbulde",
          "bülbül mahallesinde",
          "bulbul mahallesinde"
    ],
  },
  {
    name: "Yenimahalle",
    aliases: [
          "yenimahalle",
          "yeni mahalle",
          "yenimahalle mah",
          "yenimahallede",
          "yeni mahallede",
          "yenimahalle mahallesinde",
          "yeni mahalle mh"
    ],
  },
  {
    name: "Merkez",
    aliases: [
          "merkez mahallesi",
          "merkez mah",
          "merkez",
          "sehir merkezi",
          "şehir merkezi",
          "kent merkezi",
          "merkezde",
          "çarşı",
          "carsi",
          "çarşı merkezi",
          "carsi merkezi",
          "merkez mahalle",
          "kent içi",
          "kent ici"
    ],
  }
];
